### ISSUE TITLE
Can i be part of staff pls

### ISSUE THREAD

**Issue by mgracer48** [ToontownLover/Toontown-Evolution#1]

**Comment by MacandWindows** [comment]
we are team woof? this is a great idea, mgracer has great indie experiences.

**Comment by Internetpirate** [comment]
meme

**Comment by Internetpirate** [comment]
wow josh skidder don't delete my comment sMH

**Comment by Internetpirate** [comment]
stop

deleting

my 

comments

josh

skidder
